apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo
  namespace: 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: 
  source:
    path: ./app-of-apps
    repoURL: https://github.com/jduimovich/demo-gops.git
    targetRevision: main
  destination:
    namespace: demo-gops
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: 
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true

